# Sever
server:
  port: 8080

# Spring  
spring:
  application:
    name: Cliente
    title: Challenge Vivo
    version: 1
  main:
    banner-mode: CONSOLE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5490/postgres
    username: postgres
    password: postgres
  jpa:
    ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser 
  flyway:
    enabled: false    
    locations: classpath:/db/migration
    baseline-on-migrate: false 
  
# Application
config:
  app:
    jwtSecret: AreaLogadaSecretKey
    jwtExpirationMs: 60000
    jwtRefreshTokenExpirationMs: 1296000000
    
# CRUD
crud:
  data: 
    name: 
  collection:
    namea: 
    nameb: 
    namec: 
    named: 

# API
api:
  integration-catalog-content-service:

# DOCS
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: false
  pathsToMatch: /**
    
# LOG
logging:
  level:
    org.springframework: ERROR
    br.com.vwco.onedigitalplatform: DEBUG

management:
     endpoints:
         web:
            exposure:
                include: [ "prometheus" ]