# Sever
server:
  port: 8080

# Spring  
spring:
  application:
    name: Cliente
    title: Challenge Vivo
    version: 1
  main:
    banner-mode: CONSOLE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: ${DATABASE_NAME}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser 
  flyway:
    enabled: false    
    locations: classpath:/db/migration
    baseline-on-migrate: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.learning.events # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
# Application
config:
  app:
    jwtSecret: AreaLogadaSecretKey
    jwtExpirationMs: 60000
    jwtRefreshTokenExpirationMs: 1296000000
    
# CRUD
crud:
  data: 
    name: 
  collection:
    namea: 
    nameb: 
    namec: 
    named: 

# API
api:
  integration-catalog-content-service:

#azure:
 # client-id: ${AZURE_CLIENT_ID} 
  #tenant-id: ${AZURE_TENANT_ID}
  #client-secret: ${AZURE_CLIENT_SECRET}


# DOCS
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: false
  pathsToMatch: /**
    
# LOG
logging:
  level:
    org.springframework: ERROR
    br.com.fiap.products: DEBUG

management:
     endpoints:
         health: 
           enabled: true
         web:
            exposure:
                include: [ "*" ]
         jmx:
            exposure: 
                include: health			