# Sever
server:
  port: 8080

# Spring  
spring:
  application:
    name: Nome do Serviço
    title: Challange Vivo
    version: 1
  main:
    banner-mode: CONSOLE
  #POSTGRESQL 
#  postgresql:
#    datasource:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url: jdbc:postgresql://localhost:54331/postgres
#      username: postgres
#      password: postgres
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #H2
  h2:
   console:
     enabled: true
     path: /h2-ui
  datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: 
      driverClassName: org.h2.Driver
  jpa:
    properties:
      open-in-view: false
    generate-ddl: true 
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      show_sql: true
      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser
# CRUD
crud:
  data: 
    name: cripto
  collection:
    namea: BitgoOrderBooks
    nameb: BitstampOrderBooks
    namec: InternalQuotes
    named: Price

# DOCS
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: false
  pathsToMatch: /**
    
# LOG
logging:
  level:
    org.springframework: ERROR
    br.com.vwco.onedigitalplatform: DEBUG

    
# Actuator
management:
  server:
    port: 8081
  port: 9000
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
      base-path: /management
    enabled-by-default: false
    info:
      enabled: true
    jmx:
      exposure:
        include: health,info
  context-path: /manage
  endpoint:
    shutdown:
      enabled: true

#flyway
# TODO - - Validar com segurança e TI
flyway:
  enabled: true    
  locations: classpath:/db/migration
  baseline-on-migrate: true 
